
spring.application.name=SIGEBI
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/SIGEBI2
spring.datasource.username=postgres
spring.datasource.password=20251126
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=SIGEBI-Hikari
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE