spring.application.name=SIGEBI
spring.datasource.url=jdbc:postgresql://localhost:5432/SIGEBI2
spring.datasource.username=postgres
spring.datasource.password=20251126

spring.jpa.hibernate.ddl-auto=validate